config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :recipes  #recipesのmodelではrecipesのデータベースのみが紐づけされているためここにcaloriesのテーブルも紐づける
  post "recipes/search" => "recipes#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user #これなんだ！！！調べる
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy # ユーザーアカウントを消去したらレシピも消去される
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
   
   private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipes = Recipe.all
    @recipe = Recipe.new

  end

  def search
      name = params[:name]
      num = params[:num]

      select_data = Calorie.find_by(name: "#{name}")
      @name = select_data["name"]
  
      @total = select_data["calorie"].to_i * num.to_i / 100

      p @total
  
       
  end

  def create
  

    respond_to do |format|
      if  @symbol==:js
        binding.pry
        name = params[:name]
        num = params[:num]
    
        logger.debug(@calorie)#確認
        @select_data = Calorie.find_by(params[:name])
        logger.debug(@select_data)#確認
    
        @total = select_data["calorie"].to_i * num.to_i / 100

        p @total
    
        format.js { redirect_to }
        
      else
        
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.save
    redirect_to recipe_path(@recipe)
      end
        
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  private
  
  def recipe_params
    params.require(:recipe).permit(:title, :body)
    #保存内容が後で増える食材のidを付け加えたい
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartcalorieDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert]%>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">smartcalorie</h1>
        <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/recipes/_calorie.html.erb
<li class="recipe"><%= recipe.body %></li>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ編集
      </h1>
    </div>
  </div>
</section>

<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

<%= render @recipes %>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規レシピ作成
      </h1>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
   
            <%# 料理写真を追加する %>
            <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>


<div class="contents">
  <%= form_with url: 'search', class: 'js-form', local: false do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :num%>
    <%= f.submit %>
  <% end %>
</div>
<ul class="result">
  
</ul>

<%# 結果を反映させるための領域を確保  %>
<%#<ul id="result"></ul>%>


 
 

app/views/recipes/search.js.erb
$(function(){
    $('.result').append("<li><%= @name %></li><li class='calorie'><%= @total %></li>");
});
$('.js-form')[0].reset();

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
        　<div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @recipe.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.body %></td>
                </tr>
              </table>
              <% if @recipe.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_recipe_path(@recipe), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>


<%= form_for @user do |f|%>

<%= f.label :username%>
<%= f.text_field :username%>

<%= f.label :emai%>
<%= f.text_field :email%>

<%= f.label :profile%>
<%= f.text_field :profile%>

<% end %>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピグラマー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">

                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= @user.username %>

<%= @user.email%>